"""create tickets table

Revision ID: 55a56339c11c
Revises: 0d68b63175d2
Create Date: 2026-09-19 14:22:10.546136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a56339c11c'
down_revision: Union[str, Sequence[str], None] = '0d68b63175d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('microsoft_365', 'hardware', 'network', 'software', 'printer', 'other', name='ticket_category', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='ticket_priority', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticket_status', native_enum=False, create_constraint=True, length=20), server_default='open', nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
