"""create it requests table

Revision ID: 8978dda3b4d3
Revises: 55a56339c11c
Create Date: 2026-09-19 17:12:56.512225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8978dda3b4d3'
down_revision: Union[str, Sequence[str], None] = '55a56339c11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('request_type', sa.Enum('software_installation', 'account_creation', 'vpn_access', 'permission_request', 'hardware_request', 'other', name='request_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'rejected', name='request_status', native_enum=False, create_constraint=True, length=30), server_default='pending', nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('it_requests')
    # ### end Alembic commands ###
