"""create asset assignments table

Revision ID: ed4642bbdf91
Revises: ccef3dd482ab
Create Date: 2026-09-20 04:30:43.431797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4642bbdf91'
down_revision: Union[str, Sequence[str], None] = 'ccef3dd482ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_asset_assignments_active_asset', 'asset_assignments', ['asset_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_asset_assignments_active_asset', table_name='asset_assignments', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_table('asset_assignments')
    # ### end Alembic commands ###
